alias songs="cd /media/atharva/CANAJ/LAPTOPBACKUP/SONGS && rhythmbox ."
alias soub="source ~/.bashrc"
alias atomba="atom ~/.bash_aliases"
alias atombrc="atom ~/.bashrc"
alias cra='function _(){ npx create-react-app $1 --template cra-template-pwa;}; _'
alias cls="clear"
alias mkcd='function _(){ mkdir $1 && cd $1; }; _'
alias catba="cat ~/.bash_aliases"
alias debF="cd ~/Downloads/deb"
alias mountWindows="cd ~/Desktop/windows && mount /dev/sda3 ."
alias pdfs="cd /home/atharva/Desktop/windows/college\ pdfs/6th/"
alias pip="pip3"
alias cRun='function _(){ cc $1.c -o $1.out ;./$1.out; }; _'
alias opengl='function _(){ cc $1.c -lGLU -lGL -lglut -o $1.out&& mv ./$1.out ./out/ && ./out/$1.out; }; _'
alias sslab='function _(){ lex $1.l && cc lex.yy.c -ll -o $1.out && ./$1.out; }; _'
alias ftpStart='sudo systemctl start vsftpd'
alias ftpStatus='sudo systemctl status vsftpd'
alias ftpStop='sudo systemctl stop vsftpd'
alias upg='sudo apt update && sudo apt upgrade -y'
